name: Lightweight smoke test

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run lightweight smoke test
        run: |
          python .github/smoke/smoke_test.py
          
